### ISSUE TITLE
Jeffrey / app / controllers / projetosController.php => Retornar o array e tratar a variável na camada view.

### ISSUE THREAD

**Issue by kyrvim** [junniior/Jeffrey#1]
Na teoria, não vejo como não funcionar, segundo o Mark, quando a view chamar o método.... ele vai retornar uma a variável correspondente a consulta na camada Model.

public function listaProjetos( $string ) {
            $db = new Projetos_Model();
            $read = ($db->read('sis_pjt'));
                        return $read;
                        }

Então, a view vai tratar as informações como um array normalmente. Vou tentar o procedimento.

**Comment by junniior** [comment]
Executado.
